language: r
pandoc_version: 2.2
sudo: false
dist: trusty
cache: packages

before_script:
  - R CMD INSTALL .
  - cd inst/examples
  - Rscript -e "bookdown::render_book('index.Rmd', 'jayhawkdown::thesis_pdf')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - cd ../..

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  on:
    branch: master
  local-dir: inst/examples/_book/
