language: r
pandoc_version: 2.2
sudo: false
dist: trusty
cache:
  packages: true
  directories:
    - $HOME/.npm

before_install:
  - nvm install stable
  - npm install netlify-cli -g

before_script:
  - R CMD INSTALL .
  - cd inst/examples
  - Rscript -e "bookdown::render_book('index.Rmd', 'jayhawkdown::thesis_pdf')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - cd ../..

deploy:
  provider: script
  script: netlify deploy --prod --dir inst/examples/_book
  skip_cleanup: true
