# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache: packages
latex: false

include:
- r: release
- r: oldrel
- r: devel

repos:
  CRAN: https://cran.rstudio.com/
  KRAN: http://rweb.crmda.ku.edu/kran/

install:
- travis_wait R -e 'devtools::install_deps(dep = T)'
