language: r
pandoc_version: 2.2
sudo: false
dist: trusty
cache: packages

before_script:
  - R CMD INSTALL .
  - cd inst/examples
  - Rscript -e "bookdown::render_book('index.Rmd', 'jayhawkdown::thesis_pdf')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - cd ../..

after_success:
  - cd inst/examples
  - chmod +x ./_deploy.sh
  - ./_deploy.sh
